# Form implementation generated from reading ui file 'qtMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qtMainWindow(object):
    def setupUi(self, qtMainWindow):
        qtMainWindow.setObjectName("qtMainWindow")
        qtMainWindow.resize(864, 600)
        qtMainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=qtMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameDeBodegas = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameDeBodegas.setStyleSheet("QFrame{\n"
"background-color:rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font:87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:black;\n"
"}")
        self.frameDeBodegas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameDeBodegas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameDeBodegas.setObjectName("frameDeBodegas")
        self.widget = QtWidgets.QWidget(parent=self.frameDeBodegas)
        self.widget.setGeometry(QtCore.QRect(0, 210, 852, 151))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qtBTNCreacionDeBodegas = QtWidgets.QPushButton(parent=self.widget)
        self.qtBTNCreacionDeBodegas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNCreacionDeBodegas.setStyleSheet("background-color:rgb(0, 0, 0)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/truck (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.qtBTNCreacionDeBodegas.setIcon(icon)
        self.qtBTNCreacionDeBodegas.setIconSize(QtCore.QSize(18, 18))
        self.qtBTNCreacionDeBodegas.setObjectName("qtBTNCreacionDeBodegas")
        self.horizontalLayout_2.addWidget(self.qtBTNCreacionDeBodegas)
        self.qtBTNModificaInventarios = QtWidgets.QPushButton(parent=self.widget)
        self.qtBTNModificaInventarios.setStyleSheet("background-color:rgb(0, 0, 0)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/edit-3 (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.qtBTNModificaInventarios.setIcon(icon1)
        self.qtBTNModificaInventarios.setObjectName("qtBTNModificaInventarios")
        self.horizontalLayout_2.addWidget(self.qtBTNModificaInventarios)
        self.qtBTNRegistroDeArticulos = QtWidgets.QPushButton(parent=self.widget)
        self.qtBTNRegistroDeArticulos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNRegistroDeArticulos.setStyleSheet("background-color:rgb(0, 0, 0)")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/list (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.qtBTNRegistroDeArticulos.setIcon(icon2)
        self.qtBTNRegistroDeArticulos.setIconSize(QtCore.QSize(18, 18))
        self.qtBTNRegistroDeArticulos.setObjectName("qtBTNRegistroDeArticulos")
        self.horizontalLayout_2.addWidget(self.qtBTNRegistroDeArticulos)
        self.qtBTNGestionDeBodegas = QtWidgets.QPushButton(parent=self.widget)
        self.qtBTNGestionDeBodegas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNGestionDeBodegas.setStyleSheet("background-color:rgb(0, 0, 0)")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/folder (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.qtBTNGestionDeBodegas.setIcon(icon3)
        self.qtBTNGestionDeBodegas.setIconSize(QtCore.QSize(15, 15))
        self.qtBTNGestionDeBodegas.setObjectName("qtBTNGestionDeBodegas")
        self.horizontalLayout_2.addWidget(self.qtBTNGestionDeBodegas)
        self.horizontalLayout.addWidget(self.frameDeBodegas)
        qtMainWindow.setCentralWidget(self.centralwidget)
        self.qtMenuBar = QtWidgets.QMenuBar(parent=qtMainWindow)
        self.qtMenuBar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.qtMenuBar.setObjectName("qtMenuBar")
        self.menuMenu_Principal = QtWidgets.QMenu(parent=self.qtMenuBar)
        self.menuMenu_Principal.setObjectName("menuMenu_Principal")
        qtMainWindow.setMenuBar(self.qtMenuBar)
        self.actionCreacion_De_Bodegas = QtGui.QAction(parent=qtMainWindow)
        self.actionCreacion_De_Bodegas.setObjectName("actionCreacion_De_Bodegas")
        self.actionManejo_De_Bodegas = QtGui.QAction(parent=qtMainWindow)
        self.actionManejo_De_Bodegas.setObjectName("actionManejo_De_Bodegas")
        self.qtMNUSalir = QtGui.QAction(parent=qtMainWindow)
        self.qtMNUSalir.setObjectName("qtMNUSalir")
        self.actionCreacion_De_Bodegas_2 = QtGui.QAction(parent=qtMainWindow)
        self.actionCreacion_De_Bodegas_2.setObjectName("actionCreacion_De_Bodegas_2")
        self.menuMenu_Principal.addAction(self.qtMNUSalir)
        self.qtMenuBar.addAction(self.menuMenu_Principal.menuAction())

        self.retranslateUi(qtMainWindow)
        QtCore.QMetaObject.connectSlotsByName(qtMainWindow)

    def retranslateUi(self, qtMainWindow):
        _translate = QtCore.QCoreApplication.translate
        qtMainWindow.setWindowTitle(_translate("qtMainWindow", "CDP || Bodegas"))
        self.qtBTNCreacionDeBodegas.setText(_translate("qtMainWindow", "Creacion De Bodegas"))
        self.qtBTNModificaInventarios.setText(_translate("qtMainWindow", "Modificar Inventarios"))
        self.qtBTNRegistroDeArticulos.setText(_translate("qtMainWindow", "Registro De Articulos"))
        self.qtBTNGestionDeBodegas.setText(_translate("qtMainWindow", "Gestion De Bodegas"))
        self.menuMenu_Principal.setTitle(_translate("qtMainWindow", "Menu Principal"))
        self.actionCreacion_De_Bodegas.setText(_translate("qtMainWindow", "Creacion De Bodegas"))
        self.actionManejo_De_Bodegas.setText(_translate("qtMainWindow", "Manejo De Bodegas"))
        self.qtMNUSalir.setText(_translate("qtMainWindow", "Salir"))
        self.actionCreacion_De_Bodegas_2.setText(_translate("qtMainWindow", "Creacion De Bodegas"))
