# Form implementation generated from reading ui file 'qtWDWgregarBodega.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qtWDWAgregarBodega(object):
    def setupUi(self, qtWDWAgregarBodega):
        qtWDWAgregarBodega.setObjectName("qtWDWAgregarBodega")
        qtWDWAgregarBodega.resize(400, 300)
        self.qtBTNAgregarBodega = QtWidgets.QPushButton(parent=qtWDWAgregarBodega)
        self.qtBTNAgregarBodega.setGeometry(QtCore.QRect(80, 220, 101, 23))
        self.qtBTNAgregarBodega.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNAgregarBodega.setObjectName("qtBTNAgregarBodega")
        self.qtBTNlimpiar = QtWidgets.QPushButton(parent=qtWDWAgregarBodega)
        self.qtBTNlimpiar.setGeometry(QtCore.QRect(210, 220, 101, 23))
        self.qtBTNlimpiar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNlimpiar.setObjectName("qtBTNlimpiar")
        self.label = QtWidgets.QLabel(parent=qtWDWAgregarBodega)
        self.label.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.label.setObjectName("label")
        self.qtTXTNombreDeBodega = QtWidgets.QLineEdit(parent=qtWDWAgregarBodega)
        self.qtTXTNombreDeBodega.setGeometry(QtCore.QRect(150, 110, 221, 20))
        self.qtTXTNombreDeBodega.setObjectName("qtTXTNombreDeBodega")

        self.retranslateUi(qtWDWAgregarBodega)
        QtCore.QMetaObject.connectSlotsByName(qtWDWAgregarBodega)

    def retranslateUi(self, qtWDWAgregarBodega):
        _translate = QtCore.QCoreApplication.translate
        qtWDWAgregarBodega.setWindowTitle(_translate("qtWDWAgregarBodega", "CDP || Agregar Bodega"))
        self.qtBTNAgregarBodega.setText(_translate("qtWDWAgregarBodega", "Agregar Bodega"))
        self.qtBTNlimpiar.setText(_translate("qtWDWAgregarBodega", "Limpiar"))
        self.label.setText(_translate("qtWDWAgregarBodega", "Nombre De La Bodega"))
