# Form implementation generated from reading ui file 'qtWDWRegistroDeArticulos.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qtWDWRegistroDeArticulos(object):
    def setupUi(self, qtWDWRegistroDeArticulos):
        qtWDWRegistroDeArticulos.setObjectName("qtWDWRegistroDeArticulos")
        qtWDWRegistroDeArticulos.resize(400, 300)
        self.qtBTNAgregarArticulo = QtWidgets.QPushButton(parent=qtWDWRegistroDeArticulos)
        self.qtBTNAgregarArticulo.setGeometry(QtCore.QRect(70, 220, 111, 23))
        self.qtBTNAgregarArticulo.setObjectName("qtBTNAgregarArticulo")
        self.qtBTNLimpiar = QtWidgets.QPushButton(parent=qtWDWRegistroDeArticulos)
        self.qtBTNLimpiar.setGeometry(QtCore.QRect(210, 220, 111, 23))
        self.qtBTNLimpiar.setObjectName("qtBTNLimpiar")
        self.label = QtWidgets.QLabel(parent=qtWDWRegistroDeArticulos)
        self.label.setGeometry(QtCore.QRect(30, 30, 47, 13))
        self.label.setObjectName("label")
        self.qtTXTNombre = QtWidgets.QLineEdit(parent=qtWDWRegistroDeArticulos)
        self.qtTXTNombre.setGeometry(QtCore.QRect(110, 30, 251, 20))
        self.qtTXTNombre.setObjectName("qtTXTNombre")
        self.label_2 = QtWidgets.QLabel(parent=qtWDWRegistroDeArticulos)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.qtTXTPrecio = QtWidgets.QLineEdit(parent=qtWDWRegistroDeArticulos)
        self.qtTXTPrecio.setGeometry(QtCore.QRect(110, 80, 251, 20))
        self.qtTXTPrecio.setObjectName("qtTXTPrecio")
        self.label_3 = QtWidgets.QLabel(parent=qtWDWRegistroDeArticulos)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.qtSPNSpinCantidad = QtWidgets.QSpinBox(parent=qtWDWRegistroDeArticulos)
        self.qtSPNSpinCantidad.setGeometry(QtCore.QRect(110, 120, 42, 22))
        self.qtSPNSpinCantidad.setObjectName("qtSPNSpinCantidad")

        self.retranslateUi(qtWDWRegistroDeArticulos)
        QtCore.QMetaObject.connectSlotsByName(qtWDWRegistroDeArticulos)

    def retranslateUi(self, qtWDWRegistroDeArticulos):
        _translate = QtCore.QCoreApplication.translate
        qtWDWRegistroDeArticulos.setWindowTitle(_translate("qtWDWRegistroDeArticulos", "CDP || Registro De Articulos"))
        self.qtBTNAgregarArticulo.setText(_translate("qtWDWRegistroDeArticulos", "Agregar Articulo"))
        self.qtBTNLimpiar.setText(_translate("qtWDWRegistroDeArticulos", "Limpiar"))
        self.label.setText(_translate("qtWDWRegistroDeArticulos", "Nombre"))
        self.label_2.setText(_translate("qtWDWRegistroDeArticulos", "Precio"))
        self.label_3.setText(_translate("qtWDWRegistroDeArticulos", "Cantidad"))
