# Form implementation generated from reading ui file 'qtMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qtMainWindow(object):
    def setupUi(self, qtMainWindow):
        qtMainWindow.setObjectName("qtMainWindow")
        qtMainWindow.resize(800, 600)
        qtMainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=qtMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qtBTNCreacionDeBodegas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.qtBTNCreacionDeBodegas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNCreacionDeBodegas.setObjectName("qtBTNCreacionDeBodegas")
        self.horizontalLayout.addWidget(self.qtBTNCreacionDeBodegas)
        self.qtBTNModificarInventarios = QtWidgets.QPushButton(parent=self.centralwidget)
        self.qtBTNModificarInventarios.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNModificarInventarios.setObjectName("qtBTNModificarInventarios")
        self.horizontalLayout.addWidget(self.qtBTNModificarInventarios)
        self.qtBTNRegistroDeArticulos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.qtBTNRegistroDeArticulos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNRegistroDeArticulos.setObjectName("qtBTNRegistroDeArticulos")
        self.horizontalLayout.addWidget(self.qtBTNRegistroDeArticulos)
        self.qtBTNGestionDeBodegas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.qtBTNGestionDeBodegas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qtBTNGestionDeBodegas.setObjectName("qtBTNGestionDeBodegas")
        self.horizontalLayout.addWidget(self.qtBTNGestionDeBodegas)
        qtMainWindow.setCentralWidget(self.centralwidget)
        self.qtMenuBar = QtWidgets.QMenuBar(parent=qtMainWindow)
        self.qtMenuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.qtMenuBar.setObjectName("qtMenuBar")
        self.menuMenu_Principal = QtWidgets.QMenu(parent=self.qtMenuBar)
        self.menuMenu_Principal.setObjectName("menuMenu_Principal")
        qtMainWindow.setMenuBar(self.qtMenuBar)
        self.statusbar = QtWidgets.QStatusBar(parent=qtMainWindow)
        self.statusbar.setObjectName("statusbar")
        qtMainWindow.setStatusBar(self.statusbar)
        self.actionCreacion_De_Bodegas = QtGui.QAction(parent=qtMainWindow)
        self.actionCreacion_De_Bodegas.setObjectName("actionCreacion_De_Bodegas")
        self.actionManejo_De_Bodegas = QtGui.QAction(parent=qtMainWindow)
        self.actionManejo_De_Bodegas.setObjectName("actionManejo_De_Bodegas")
        self.qtMNUSalir = QtGui.QAction(parent=qtMainWindow)
        self.qtMNUSalir.setObjectName("qtMNUSalir")
        self.actionCreacion_De_Bodegas_2 = QtGui.QAction(parent=qtMainWindow)
        self.actionCreacion_De_Bodegas_2.setObjectName("actionCreacion_De_Bodegas_2")
        self.menuMenu_Principal.addAction(self.qtMNUSalir)
        self.qtMenuBar.addAction(self.menuMenu_Principal.menuAction())

        self.retranslateUi(qtMainWindow)
        QtCore.QMetaObject.connectSlotsByName(qtMainWindow)

    def retranslateUi(self, qtMainWindow):
        _translate = QtCore.QCoreApplication.translate
        qtMainWindow.setWindowTitle(_translate("qtMainWindow", "CDP || Bodegas"))
        self.qtBTNCreacionDeBodegas.setText(_translate("qtMainWindow", "Creacion De Bodegas"))
        self.qtBTNModificarInventarios.setText(_translate("qtMainWindow", "Modificar Inventarios"))
        self.qtBTNRegistroDeArticulos.setText(_translate("qtMainWindow", "Registro De Articulos"))
        self.qtBTNGestionDeBodegas.setText(_translate("qtMainWindow", "Gestion De Bodegas"))
        self.menuMenu_Principal.setTitle(_translate("qtMainWindow", "Menu Principal"))
        self.actionCreacion_De_Bodegas.setText(_translate("qtMainWindow", "Creacion De Bodegas"))
        self.actionManejo_De_Bodegas.setText(_translate("qtMainWindow", "Manejo De Bodegas"))
        self.qtMNUSalir.setText(_translate("qtMainWindow", "Salir"))
        self.actionCreacion_De_Bodegas_2.setText(_translate("qtMainWindow", "Creacion De Bodegas"))
