# Form implementation generated from reading ui file 'qtWDWInventarios.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qtWDWInventarios(object):
    def setupUi(self, qtWDWInventarios):
        qtWDWInventarios.setObjectName("qtWDWInventarios")
        qtWDWInventarios.resize(601, 415)
        self.label = QtWidgets.QLabel(parent=qtWDWInventarios)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=qtWDWInventarios)
        self.comboBox.setGeometry(QtCore.QRect(80, 10, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.tableWidget = QtWidgets.QTableWidget(parent=qtWDWInventarios)
        self.tableWidget.setGeometry(QtCore.QRect(240, 10, 311, 381))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(qtWDWInventarios)
        QtCore.QMetaObject.connectSlotsByName(qtWDWInventarios)

    def retranslateUi(self, qtWDWInventarios):
        _translate = QtCore.QCoreApplication.translate
        qtWDWInventarios.setWindowTitle(_translate("qtWDWInventarios", "CDP || Inventarios"))
        self.label.setText(_translate("qtWDWInventarios", "Bodega"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("qtWDWInventarios", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("qtWDWInventarios", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("qtWDWInventarios", "Cantidad"))
