# Form implementation generated from reading ui file 'qtWDWControlDeBodegas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qtWDWControlDeBodegas(object):
    def setupUi(self, qtWDWControlDeBodegas):
        qtWDWControlDeBodegas.setObjectName("qtWDWControlDeBodegas")
        qtWDWControlDeBodegas.resize(949, 342)
        self.frame = QtWidgets.QFrame(parent=qtWDWControlDeBodegas)
        self.frame.setGeometry(QtCore.QRect(-100, -80, 1091, 441))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font:87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:black;\n"
"}\n"
"\n"
"QLabel{\n"
"font:87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white;\n"
"}\n"
"\n"
"QSpinBox{\n"
"font:87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white;\n"
"}\n"
"\n"
"QComboBox{\n"
"font:87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.qtTXEControlDeCambios = QtWidgets.QTextEdit(parent=self.frame)
        self.qtTXEControlDeCambios.setGeometry(QtCore.QRect(520, 150, 501, 261))
        self.qtTXEControlDeCambios.setStyleSheet("background:white")
        self.qtTXEControlDeCambios.setObjectName("qtTXEControlDeCambios")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(520, 110, 101, 31))
        self.label_5.setStyleSheet("background:black")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(140, 140, 81, 31))
        self.label.setStyleSheet("background:black\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.qtCMBEmisor_2 = QtWidgets.QComboBox(parent=self.frame)
        self.qtCMBEmisor_2.setGeometry(QtCore.QRect(270, 140, 161, 22))
        self.qtCMBEmisor_2.setStyleSheet("background:black")
        self.qtCMBEmisor_2.setObjectName("qtCMBEmisor_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(140, 260, 101, 31))
        self.label_4.setStyleSheet("background:black")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 180, 101, 31))
        self.label_2.setStyleSheet("background:black")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 220, 91, 31))
        self.label_3.setStyleSheet("background:black\n"
"")
        self.label_3.setObjectName("label_3")
        self.qtSPNCantidadDeArticulos = QtWidgets.QSpinBox(parent=self.frame)
        self.qtSPNCantidadDeArticulos.setGeometry(QtCore.QRect(280, 270, 131, 31))
        self.qtSPNCantidadDeArticulos.setStyleSheet("background:black")
        self.qtSPNCantidadDeArticulos.setObjectName("qtSPNCantidadDeArticulos")
        self.qtCMBReceptor = QtWidgets.QComboBox(parent=self.frame)
        self.qtCMBReceptor.setGeometry(QtCore.QRect(270, 180, 161, 22))
        self.qtCMBReceptor.setStyleSheet("background:black")
        self.qtCMBReceptor.setObjectName("qtCMBReceptor")
        self.qtCMBArticulos = QtWidgets.QComboBox(parent=self.frame)
        self.qtCMBArticulos.setGeometry(QtCore.QRect(270, 230, 161, 22))
        self.qtCMBArticulos.setStyleSheet("background:black")
        self.qtCMBArticulos.setObjectName("qtCMBArticulos")
        self.qtBTNLimpiar = QtWidgets.QPushButton(parent=self.frame)
        self.qtBTNLimpiar.setGeometry(QtCore.QRect(310, 340, 101, 31))
        self.qtBTNLimpiar.setStyleSheet("background:black")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/book.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.qtBTNLimpiar.setIcon(icon)
        self.qtBTNLimpiar.setIconSize(QtCore.QSize(17, 17))
        self.qtBTNLimpiar.setObjectName("qtBTNLimpiar")
        self.qtBTNEnviar = QtWidgets.QPushButton(parent=self.frame)
        self.qtBTNEnviar.setGeometry(QtCore.QRect(170, 340, 101, 31))
        self.qtBTNEnviar.setStyleSheet("background:black")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/log-in.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.qtBTNEnviar.setIcon(icon1)
        self.qtBTNEnviar.setIconSize(QtCore.QSize(20, 23))
        self.qtBTNEnviar.setObjectName("qtBTNEnviar")

        self.retranslateUi(qtWDWControlDeBodegas)
        QtCore.QMetaObject.connectSlotsByName(qtWDWControlDeBodegas)

    def retranslateUi(self, qtWDWControlDeBodegas):
        _translate = QtCore.QCoreApplication.translate
        qtWDWControlDeBodegas.setWindowTitle(_translate("qtWDWControlDeBodegas", "CDP || Control De Bogedas"))
        self.label_5.setText(_translate("qtWDWControlDeBodegas", "Cambios:"))
        self.label.setText(_translate("qtWDWControlDeBodegas", "Emisor:"))
        self.label_4.setText(_translate("qtWDWControlDeBodegas", "Articulos:"))
        self.label_2.setText(_translate("qtWDWControlDeBodegas", "Receptor:"))
        self.label_3.setText(_translate("qtWDWControlDeBodegas", "Articulo:"))
        self.qtBTNLimpiar.setText(_translate("qtWDWControlDeBodegas", "Limpiar"))
        self.qtBTNEnviar.setText(_translate("qtWDWControlDeBodegas", "Enviar"))
